[tool.black]
line-length = 100
target_version = ['py37']
include = '''
(
  ethicml/(.*).pyi?$
  | tests/(.*).pyi?$
)
'''
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.venv
    | .*/\.venv
    | _build
    | buck-out
    | build
    | dist
    | .github
    | docs
    | docsource
    | examples
    | plots
    | results
    | \.editorconfig
    | \.gitignore
    | \.pytest_cache
    | \.coverage.*
    | .pre-commit-config.yaml
    | .pylintrc
    | CODEOWNERS
    | LICENSE
    | mypy.ini
    | README.md
  )/
)
'''
skip-string-normalization = true
