"""
Numpy's mypy stub. Only type declarations for ndarray, the scalar hierarchy and array creation
methods are provided.
"""

from typing import (Any, Callable, Dict, Generic, Iterator, List, Optional, Sequence, Tuple, Type,
                    TypeVar, Union)

class dtype: ...
_dtype = dtype

_Scalar = TypeVar('_Scalar')

ShapeType = Union[int, Tuple[int, ...]]
AxesType = Union[int, Tuple[int, ...]]
OrderType = Union[str, Sequence[str]]
DtypeType = Union[dtype, type]

class ndarray:
    """
    "array-like" interface that both numpy.ndarray and all scalars (descendants of numpy.generic)
    implement this interface.
    """
    #
    # Array-like structures attributes
    #
    dtype: _dtype
    size: int
    ndim: int
    shape: Tuple[int, ...]

    #
    # Array-like methods
    #

    # Once this issue https://github.com/python/mypy/issues/1907 is resolved, most methods that
    # have an 'out' argument, will be implemented using overload instead of with a Union
    # result. mypy is smart enough to assign the proper type (_ArrayLike[_U]) when out is present
    # but it falls back to the union when it's not.
    def __init__(self, shape: Tuple[int, ...], dtype: DtypeType=None,
                 buffer: Any=None, offset: int=None,
                 strides: Tuple[int, ...]=None, order: str=None) -> None: ...
    def all(self, axis: AxesType=None, out: ndarray=None,
            keepdims: bool=False) -> Union[ndarray, ndarray]: ...

    def any(self, axis: AxesType=None, out: ndarray=None,
            keepdims: bool=False) -> Union[ndarray, ndarray]: ...

    def argmax(self, axis: int=None,
               out: ndarray=None) -> Union[ndarray, ndarray]: ...

    def argmin(self, axis: int=None,
               out: ndarray=None) -> Union[ndarray, ndarray]: ...

    def argpartition(self, kth: Union[int, Sequence[int]], axis: Optional[int]=-1,
                     kind: str='introselect', order: OrderType=None) -> ndarray: ...

    def argsort(self, axis: int=None, kind: str='quicksort',
                order: OrderType=None) -> ndarray: ...

    def astype(self, dtype: Any, order: str='K', casting: str='unsafe', subok: bool=True,
               copy: bool=False) -> ndarray: ...

    def byteswap(self, inplace: bool=False) -> ndarray: ...

    def choose(self, choices:Sequence[ndarray], out: ndarray=None,
               mode: str='raise') ->  Union[ndarray, ndarray]: ...

    def clip(self, a_min: Any, a_max: Any,
             out: ndarray=None) -> Union[ndarray, ndarray]: ...

    def compress(self, condition: Sequence[bool], axis: int=None,
                 out: ndarray=None) -> Union[ndarray, ndarray]: ...

    def conj(self) -> ndarray: ...

    def conjugate(self) -> ndarray: ...

    def copy(self, order: str='C') -> ndarray: ...

    def cumprod(self, axis: int=None, dtype: Any=None,
                out: ndarray=None) -> ndarray: ...

    def cumsum(self, axis: int=None, dtype: DtypeType=None,
                out: ndarray=None) -> ndarray: ...

    def diagonal(self, offset: int=0, axis1: int=0, axis2: int=1) -> ndarray: ...

    def dot(self, b: ndarray, out: ndarray=None) -> ndarray: ...

    def dump(self, file: str) -> None: ...

    def dumps(self) -> str: ...

    # def fill(self, value: _S) -> None: ...

    def flatten(self, order: str='C') -> ndarray: ...

    def getfield(self, dtype: DtypeType, offset: int=0) -> ndarray: ...

    def item(self, args: AxesType = None) -> float: ...

    def itemset(self, arg0: Union[int, Tuple[int, ...]], arg1: Any=None) -> None: ...

    def max(self, axis: AxesType=None,
            out: ndarray=None) -> Union[ndarray, ndarray]: ...

    def mean(self, axis: AxesType=None, dtype: Any=None,
             out: ndarray=None, keepdims: bool=False) -> ndarray: ...

    def min(self, axis: AxesType=None,
            out: ndarray=None) -> Union[ndarray, ndarray]: ...

    def newbyteorder(self, new_order: str='S') -> ndarray: ...

    def nonzero(self) -> ndarray: ...

    def partition(self, kth: AxesType, axis: int=-1, kind: str='introselect',
                  order: OrderType=None) -> None: ...

    def prod(self, axis: AxesType=None, dtype: DtypeType=None,
             out: ndarray=None, keepdims: bool=False) -> ndarray: ...

    def ptp(self, axis: int=None,
            out: ndarray=None) -> Union[ndarray, ndarray]: ...

    def put(self, ind: ndarray, v: ndarray, mode: str='raise') -> None: ...

    def ravel(self, order: str='C') -> ndarray: ...

    def repeat(self, repeats: Union[int, Sequence[int]],
               axis: int=None) -> ndarray: ...

    def reshape(self, newshape: ShapeType,
                order: str='C') -> ndarray: ...

    def resize(self, new_shape: ShapeType, refcheck: bool=True) -> None: ...

    def round(self, decimals: int=0,
              out: ndarray=None) -> Union[ndarray, ndarray]: ...

    # def searchsorted(self, v: Union[_S, ndarray], side: str='left',
    #                  sorter: ndarray=None) -> ndarray: ...

    def setfield(self, val: Any, dtype: DtypeType, offset: int=0) -> None: ...

    def setflags(self, write: bool=None, align: bool=None,
                 uic: bool=None) -> None: ...

    def sort(self, axis: int=-1, kind: str='quicksort', order: OrderType=None) -> None: ...

    def squeeze(self, axis: AxesType=None) -> ndarray: ...

    def std(self, axis: AxesType=None, dtype: DtypeType=None,
            out: ndarray=None, ddof: int=0, keepdims: bool=False) -> ndarray: ...

    def sum(self, axis: AxesType=None, dtype: DtypeType=None,
            out: ndarray=None,
            keepdims: bool=False) -> ndarray: ...

    def swapaxes(self, axis1: int, axis2: int) -> ndarray: ...

    def take(self, indices: Sequence[int], axis: int=None,
             out: ndarray=None,
             mode: str='raise') -> Union[ndarray, ndarray]: ...

    def tobytes(self, order: str='C') -> bytes: ...

    def tofile(self, fid: object, sep: str='',  # TODO fix fid definition (There's a bug in mypy io's namespace https://github.com/python/mypy/issues/1462)
               format: str='%s') -> None: ...

    def tolist(self) -> List: ...

    def tostring(self, order: str='C') -> bytes: ...

    def trace(self, offset: int=0, axis1: int=0, axis2: int=1,
              dtype: DtypeType=None, out: ndarray=None) -> ndarray: ...

    def transpose(self, axes: AxesType = None) -> ndarray: ...

    def var(self, axis: AxesType=None, dtype: DtypeType=None,
            out: ndarray=None, ddof: int=0, keepdims: bool=False) -> ndarray: ...

    def view(self, dtype: Union[DtypeType, Type['ndarray']]=None,
             type: type=None) -> ndarray: ...

    #
    # Magic methods
    #

    def __abs__(self) -> ndarray: ...

    def __add__(self, value: object) -> ndarray: ...

    def __and__(self, value: object) -> ndarray: ...

    def __array__(self, dtype: DtypeType=None) -> ndarray: ...

    def __array_prepare__(self, context: object=None) -> ndarray: ...

    def __array_wrap__(self, context: object=None) -> ndarray: ...

    def __bool__(self) -> bool: ...

    def __complex__(self) -> complex: ...

    def __contains__(self, key: object) -> bool: ...

    def __copy__(self) -> ndarray: ...

    def __deepcopy__(self) -> ndarray: ...

    def __delattr__(self, name: str) -> None: ...

    def __delitem__(self, key: str) -> None: ...

    def __dir__(self) -> List[str]: ...

    def __divmod__(self, value: object) -> Tuple[ndarray, ndarray]: ...

    def __eq__(self, value: object) -> ndarray: ...

    def __float__(self) -> float: ...

    def __floordiv__(self, value: object) -> ndarray: ...

    def __ge__(self, value: object) -> ndarray: ...

    def __getattribute__(self, name: str) -> Any: ...

    def __getitem__(self, key: Any) -> ndarray: ...

    def __gt__(self, value: object) -> ndarray: ...

    def __iadd__(self, value: object) -> None: ...

    def __iand__(self, value: object) -> None: ...

    def __ifloordiv__(self, value: object) -> None: ...

    def __ilshift__(self, value: object) -> None: ...

    def __imatmul__(self, value: ndarray) -> None: ...

    def __imod__(self, value: object) -> None: ...

    def __imul__(self, value: object) -> None: ...

    def __index__(self) -> int: ...

    def __int__(self) -> int: ...

    def __invert__(self) -> ndarray: ...

    def __ior__(self, value: object) -> None: ...

    def __ipow__(self, value: object) -> None: ...

    def __irshift__(self, value: object) -> None: ...

    def __isub__(self, value: object) -> None: ...

    def __iter__(self) -> Iterator: ...

    def __itruediv__(sel, value: object) -> None: ...

    def __ixor__(self, value: object) -> None: ...

    def __le__(self, value: object) -> ndarray: ...

    def __len__(self) -> int: ...

    def __lshift__(self, value: object) -> ndarray: ...

    def __lt__(self, value: object) -> ndarray: ...

    def __matmul__(self, value: ndarray) -> ndarray: ...

    def __mod__(self, value: object) -> ndarray: ...

    def __mul__(self, value: object) -> ndarray: ...

    def __ne__(self, value: object) -> ndarray: ...  # type: ignore

    def __neg__(self) -> ndarray: ...

    def __or__(self, value: object) -> ndarray: ...

    def __pos__(self) -> ndarray: ...

    def __pow__(self, value: object) -> ndarray: ...

    def __radd__(self, value: object) -> ndarray: ...

    def __rand__(self, value: object) -> ndarray: ...

    def __rdivmod__(self, value: object) -> Tuple[ndarray, ndarray]: ...

    def __rfloordiv__(self, value: object) -> ndarray: ...

    def __rlshift__(self, value: object) -> ndarray: ...

    def __rmatmul__(self, value: object) -> ndarray: ...

    def __rmod__(self, value: object) -> ndarray: ...

    def __rmul__(self, value: object) -> ndarray: ...

    def __ror__(self, value: object) -> ndarray: ...

    def __rpow__(self, value: object) -> ndarray: ...

    def __rrshift__(self, value: object) -> ndarray: ...

    def __rshift__(self, value: object) -> ndarray: ...

    def __rsub__(self, value: object) -> ndarray: ...

    def __rtruediv__(self, value: object) -> ndarray: ...

    def __rxor__(self, value: object) -> ndarray: ...

    def __setattr__(self, name: str, value: Any) -> None: ...

    def __setitem__(self, key: Any, value: Any) -> None: ...

    def __str__(self) -> str: ...

    def __sub__(self, value: object) -> ndarray: ...

    def __truediv__(sel, value: object) -> ndarray: ...

    def __xor__(self, value: object) -> ndarray: ...

#
# numpy's scalar hierarchy (http://docs.scipy.org/doc/numpy/reference/arrays.scalars.html#scalars)
#

class generic(Generic[_Scalar]): ...
class bool_(generic[bool]): ...
class number(generic[_Scalar], Generic[_Scalar]): ...
class integer(number[int]): ...
class signedinteger(integer): ...
class byte(signedinteger): ...
class short(signedinteger): ...
class intc(signedinteger): ...
class int_(signedinteger): ...
class longlong(signedinteger): ...
class int8(signedinteger): ...
class int16(signedinteger): ...
class int32(signedinteger): ...
class int64(signedinteger): ...
class unsignedinteger(integer): ...
class ubyte(unsignedinteger): ...
class ushort(unsignedinteger): ...
class uintc(unsignedinteger): ...
class uint(unsignedinteger): ...
class ulonglong(unsignedinteger): ...
class uint8(signedinteger): ...
class uint16(signedinteger): ...
class uint32(signedinteger): ...
class uint64(signedinteger): ...
class inexact(number[float]): ...
class floating(inexact): ...
class half(floating): ...
class single(floating): ...
class float_(floating): ...
class longfloat_(floating): ...
class float16(floating): ...
class float32(floating): ...
class float64(floating): ...
class float128(floating): ...
class complexfloating(inexact): ...
class csingle(complexfloating): ...
class complex_(complexfloating): ...
class clongfloat(complexfloating): ...
class complex64(complexfloating): ...
class complex128(complexfloating): ...
class complex256(complexfloating): ...
class flexible(generic[_Scalar], Generic[_Scalar]): ...
class character(flexible[str]): ...
class str_(character): ...
class unicode_(character): ...
class void(flexible[None]): ...

#
# Array creation routines
#

def array(object: Any, dtype: Any=None, copy: bool=True,
          order: str=None, subok: bool=False,
          ndmin: int=0) -> ndarray: ...
def asarray(a: Any, dtype: DtypeType=None, order: str=None) -> ndarray: ...
def ascontiguousarray(a: Any, dtype: DtypeType=None) -> ndarray: ...
def copy(a: Any, order: str=None)	-> ndarray: ...
def empty(shape: ShapeType, dtype: DtypeType=float, order: str='C') -> ndarray: ...
def empty_like(a: Any, dtype: Any=None, order: str='K', subok: bool=True) -> ndarray: ...
def eye(N: int, M: int=None, k: int=0, dtype: DtypeType=float) -> ndarray: ...
def full(shape: ShapeType, fill_value: Any, dtype: DtypeType=None,
         order: str='C') -> ndarray: ...
def full_like(a: Any, fill_value: Any, dtype: DtypeType=None, order: str='C',
              subok: bool=True) -> ndarray: ...
# def fromfunction(function: Callable[..., _S], shape: ShapeType, dtype: DtypeType=float) -> ndarray[_S]: ...
def fromiter(iterable: Iterator, dytpe: DtypeType, count: int=-1) -> ndarray: ...
def fromstring(string: str, dtype: DtypeType=float, count: int=-1, sep: str='') -> ndarray: ...
def identity(n: int, dtype: DtypeType=None) -> ndarray: ...
def loadtxt(fname: Any, dtype: DtypeType=float, comments: Union[str, Sequence[str]]='#',
            delimiter: str=None, converters: Dict[int, Callable[[Any], float]]=None,
            skiprows: int=0, usecols: Sequence[int]=None,
            unpack: bool=False, ndmin: int=0) -> ndarray: ...
def ones(shape: ShapeType, dtype: Optional[DtypeType]=..., order: str='C') -> ndarray: ...
def ones_like(a: Any, dtype: Any=None, order: str='K', subok: bool=True) -> ndarray: ...
def zeros(shape: ShapeType, dtype: DtypeType=float, order: str='C') -> ndarray: ...
def zeros_like(a: Any, dtype: Any=None, order: str='K', subok: bool=True) -> ndarray: ...

#
# Transforming functions
#

def sum(a: ndarray, axis: Union[int, List[int]] = None) -> ndarray: ...
def unique(a: ndarray) -> ndarray: ...
def where(a: ndarray) -> ndarray: ...
def astype(a: ndarray, dtype: _dtype) -> ndarray: ...
def mean(a: ndarray, axis: Union[int, List[int]] = None) -> ndarray: ...
def log(a: ndarray) -> ndarray: ...
def matmul(a: ndarray, b: ndarray) -> ndarray: ...
def expand_dims(a: ndarray, axis: Union[int, List[int]]) -> ndarray: ...
def diag(a: ndarray) -> ndarray: ...
def exp(a: ndarray) -> ndarray: ...
def trae(a: ndarray) -> ndarray: ...
def hstack(tup: Tuple[ndarray, ...]) -> ndarray: ...
def ceil(a: ndarray) -> ndarray: ...
def arange(range_: int) -> ndarray: ...
def trace(a: ndarray) -> float: ...
def split(a: ndarray, split_dims: List[int]) -> List[ndarray]: ...


class random:
    @staticmethod
    def seed(s: int): ...

    @staticmethod
    def permutation(size: int): ...

    @staticmethod
    def uniform(size: Union[int, List[int]]): ...

# Specific values
inf: float
