from ._core import _ShapeType, ndarray

def seed(s: int): ...
def permutation(size: int): ...
def uniform(size: _ShapeType): ...
def shuffle(x: ndarray) -> None: ...

class RandomState:
    def __init__(self, seed: int = ...): ...
    def shuffle(self, x: ndarray) -> None: ...
